config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :two_factor_setting, only: %i(edit update)
  resource :two_factor_qr_code, only: :show

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable, :recoverable, :rememberable, :trackable, :validatable,
         :two_factor_authenticatable,
         otp_secret_encryption_key: ENV['DEVISE_TWO_FACTOR_ENCRYPTION_KEY']

  self.otp_secret_length = 16
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) << :otp_attempt
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/two_factor_qr_codes_controller.rb
class TwoFactorQrCodesController < ApplicationController
  def show
    respond_to do |format|
      format.svg do
        render qrcode: current_user.otp_provisioning_uri(current_user.email), unit: 6
      end
    end
  end
end

app/controllers/two_factor_settings_controller.rb
class TwoFactorSettingsController < ApplicationController
  def edit
    unless current_user.otp_required_for_login?
      current_user.otp_secret = User.generate_otp_secret
      current_user.save!
    end
    render :edit, locals: {two_factor_secret: current_user.otp_secret}
  end

  def update
    if current_user.otp_required_for_login?
      disable_2fa
    else
      enable_2fa
    end
  end

  private

  def enable_2fa
    if params[:verification_code].present? && current_user.validate_and_consume_otp!(params[:verification_code])
      current_user.update!(otp_required_for_login: true)
      redirect_to root_path, notice: 'Two-factor authentication enabled!'
    else
      flash[:alert] = 'Verification code is invalid!'
      render :edit, locals: {two_factor_secret: current_user.otp_secret}
    end
  end

  def disable_2fa
    if current_user.valid_password?(params[:password])
      current_user.update!(otp_required_for_login: false)
      redirect_to root_path, notice: 'Two-factor authentication disabled!'
    else
      flash[:alert] = 'Incorrect password.'
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div><%= flash[:notice] %></div>

<% if current_user %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
  <%= link_to '2fa settings', edit_two_factor_setting_path %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Log in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devise2faExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/two_factor_settings/edit.html.erb
<h2>Two factor authentication settings</h2>

<% if current_user.otp_required_for_login? %>
  <p>
    Two factor authentication is enabled.
  </p>

  <%= form_tag(two_factor_setting_path, method: :put) do %>
    <div class="field">
      <%= label_tag 'Password' %><br />
      <%= password_field_tag :password, '', autocomplete: "off" %>
    </div>
    <%= flash[:alert] %>

    <div class="actions">
      <%= submit_tag "Disable 2fa" %>
    </div>
  <% end %>
<% else %>
  <p>
    Two factor authentication is disabled.
  </p>

  <p>
    <div>Secret</div>
    <div><%= two_factor_secret %></div>

    <img src=<%= two_factor_qr_code_path(format: :svg) %> />
  </p>

  <%= form_tag(two_factor_setting_path, method: :put) do %>
    <div class="field">
      <%= label_tag 'Verification_code' %><br />
      <%= text_field_tag :verification_code, '', autocomplete: "off" %>
    </div>
    <%= flash[:alert] %>

    <div class="actions">
      <%= submit_tag "Enable 2fa" %>
    </div>
  <% end %>
<% end %>